- name: Provision Jenkins
  hosts: all
  vars:
    jenkins_java_args: "-server -Xmx2g -Xms512m"
    jenkins_jcasc_config_file: "jenkins.yaml.j2"
    jenkins_pimt_args: "--latest false"
    jenkins_plugins_file: "plugins.yaml"
    jenkins_jobs:
      - "Trigger-seed-job"
    jenkins_jobs_dir: "{{ playbook_dir }}/files/jenkins/jobs"

  roles:
    - ansible-role-jenkins-jcasc